language: generic

services:
  - docker

before_install:
  - pwd
  - cd InventApi

jobs:
  include:
    - stage: API test
      name: "Run API test"
      script:
        - docker build -t symfony-api . 
        #- docker run image-api #mix test

    - stage: frontend tests
      name: "Run Front tests"
      script:
        - cd ../pageTelechargement 
        - docker build -t symfony-front . 
        #- docker run image-app npm #run test

    - stage: Databases
      name: "Run MySQL Databases tests"
      script:
        - cd .. 
        - docker build -t symfony-db . 
        #- docker run image-app npm #run test

    # - stage: deploy
    #   name: "Docker-compose deployment"
    #   script:
    #     - cd ..
    #     - pwd
    #     - ls
    #     - docker-compose up 
    #     - while sleep 180; do echo "Building..."; done &
    #     - kill %1
    - stage: deploy
      name: "Docker-compose deployment"
      script:
        - docker-compose up -d 
        - docker exec -it cash_manager-symfony-api-1 php bin/console doctrine:schema:update --force -vvv    
        - docker exec -it cash_manager-symfony-api-1 php bin/console doctrine:fixtures:load

