language: generic

services:
  - docker

before_install:
  - pwd
  - cd 

jobs:
  include:
    - stage: API test
      name: "Run API test"
      script:
        - cd InventApi
        - docker build -t symfony-api . 
        #- docker run image-api #mix test

    - stage: frontend tests
      name: "Run Front tests"
      script:
        - cd ../pageTelechargement 
        - docker build -t symfony-front . 
        #- docker run image-app npm #run test

    - stage: Databases
      name: "Run MySQL Databases tests"
      script:
        - cd .. 
        - docker build -t symfony-db . 
        #- docker run image-app npm #run test

    - stage: deploy
      name: "Docker-compose deployment"
      script:
        - docker-compose up -d 
    